---
config:
  theme: 'forest'
---
flowchart TD
    subgraph MDM
        direction TB
        SOURCE_TDG>transport.data.gouv.fr] --> PF_TDG("`Pipeline,
                    filtrage`")
        SOURCE_TRANSIT>transit] --> PFE_TRANSIT("`Scrapping`")
        SOURCE_OSM>openstreetmap] --> PFE_OSM("`Pipeline,
                    filtrage,
                    extraction`")
        SOURCE_C2C>camp2camp] --> PFE_C2C("`Extraction BDD`")


        PF_TDG -->|"`__transportdatagouv.py__
                    Télécharge les GTFS`"| FE_TDG("`Extraction,
                    filtrage`")
        FE_TDG -->|"`__gtf_extractor.py__
                    Extrait les arrêts et lignes`"| EXPORT_TDG[("`GeoParquet
                    GeoJSON
                    CSV`")]
        PFE_TRANSIT --> EXPORT_TRANSIT[("`transit.json`")]
        PFE_OSM --> EXPORT_OSM[("`GeoParquet
                    Geo/JSON`")]
        PFE_C2C --> EXPORT_C2C[("`CSV`")]


        EXPORT_TDG --> ANALYSE{"`Analyse
                    et regroupement
                    des données`"}
        EXPORT_TRANSIT -.-> ANALYSE
        EXPORT_OSM --> ANALYSE
        EXPORT_C2C --> ANALYSE


        ANALYSE --> IDENTIFIER["`**Identifier**
                    les données de
                    transport manquantes`"]
        ANALYSE --> REPERER["`**Repérer**
                    les topos C2C
                    non accessibles
                    en transports en commun`"]
        ANALYSE --> ENRICHIR["`**Enrichir**
                    les données`"]
        IDENTIFIER --> ARRETS_MANQUANTS["`fa:fa-bus Arrêts de bus
                    manquants`"]
        IDENTIFIER -->|...| LIGNES_MANQUANTES["`fa:fa-bus Lignes
                    manquantes`"]
        ARRETS_MANQUANTS -->|"`__visualise_stops_diff.ipynb__
                créé une carte avec un code couleur`"| DIFF((("`Carte`")))
        ENRICHIR --> PRIX[fa:fa-eur Prix]
        ENRICHIR --> VELO[fa:fa-bicycle Vélo]
        ENRICHIR --> SPECIAUX[fa:fa-graduation-cap  Réservé scolaire]

    %% Styling
        style MDM fill:#fff,stroke:#fff
        style SOURCE_TDG fill:#f96
        style SOURCE_OSM fill:#f96
        style SOURCE_C2C fill:#f96
        style SOURCE_TRANSIT fill:#f96

    %% TODO
        style PFE_C2C stroke:#f00,stroke-width:2px,stroke-dasharray: 5 5
        style LIGNES_MANQUANTES stroke:#f00,stroke-width:2px,stroke-dasharray: 5 5
    %% In progress
        style PFE_OSM stroke:#00f,stroke-width:2px
        style PF_TDG stroke:#00f,stroke-width:2px
        style FE_TDG stroke:#00f,stroke-width:2px
        style EXPORT_TDG stroke:#00f,stroke-width:2px
        style EXPORT_C2C stroke:#00f,stroke-width:2px
        style EXPORT_OSM stroke:#00f,stroke-width:2px
        style EXPORT_TRANSIT stroke:#00f,stroke-width:2px
        style ARRETS_MANQUANTS stroke:#00f,stroke-width:2px
        style DIFF stroke:#00f,stroke-width:2px
        style PFE_TRANSIT stroke:#00f,stroke-width:2px
    %% DONE
        %% style PF_TDG fill:#0d0,stroke:#333,stroke-width:4px
    end

    subgraph Légende
        direction LR
        style Légende fill:#fff
        AFaire --> EnCours --> Fini
        style AFaire stroke:#f00,stroke-width:2px,stroke-dasharray: 5 5
        style EnCours stroke:#00f,stroke-width:2px
        style Fini stroke:#333,stroke-width:4px
    end

    MDM ~~~ Légende
